# Generated by Django 5.2.4 on 2025-07-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_title', models.CharField(max_length=100)),
                ('projects_description', models.CharField(max_length=750)),
                ('projects_tags', models.CharField(max_length=200)),
                ('projects_link', models.URLField()),
            ],
        ),
    ]
