# Generated by Django 5.2.4 on 2025-07-12 07:00

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_name', models.CharField(max_length=100)),
                ('tools_image', models.ImageField(null=True, upload_to='tools/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(null=True, upload_to='posts/')),
                ('post_title_ru', models.CharField(max_length=100)),
                ('post_title_en', models.CharField(max_length=100)),
                ('post_data', models.DateField()),
                ('post_description_ru', models.CharField(max_length=750)),
                ('post_description_en', models.CharField(max_length=750)),
                ('post_link', models.URLField()),
                ('post_tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_title_ru', models.CharField(max_length=100)),
                ('projects_title_en', models.CharField(max_length=100)),
                ('projects_description_ru', models.CharField(max_length=750)),
                ('projects_description_en', models.CharField(max_length=750)),
                ('projects_link', models.URLField()),
                ('projects_tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
