# Generated by Django 5.2.4 on 2025-07-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_content_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
