# Generated by Django 5.2.4 on 2025-07-08 14:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projects_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
