# Generated by Django 5.2.4 on 2025-07-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_post_post_content_en_post_post_content_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_link',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
