# Generated by Django 5.2.4 on 2025-07-08 14:21

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_projects_projects_description'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='projects_tags',
        ),
        migrations.AddField(
            model_name='projects',
            name='projects_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
