# Generated by Django 5.2.4 on 2025-07-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_projects_projects_tags_projects_projects_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projects_description',
            field=models.CharField(max_length=750),
        ),
    ]
