# Generated by Django 5.2.4 on 2025-07-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_post_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_link',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
