# Generated by Django 5.2.4 on 2025-07-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='projects_link',
            new_name='post_link',
        ),
    ]
