# Generated by Django 5.2.4 on 2025-07-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_rename_projects_link_post_post_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='projects_tags',
            new_name='post_tags',
        ),
    ]
