# Generated by Django 5.2.4 on 2025-07-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_name', models.CharField(max_length=100)),
                ('tools_image', models.ImageField(null=True, upload_to='posts/')),
            ],
        ),
    ]
