# Generated by Django 5.2.4 on 2025-07-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='tools_image',
            field=models.ImageField(null=True, upload_to='tools/'),
        ),
    ]
